blank_issues_enabled: false
contact_links:
  - name: Chrome Web Store Reviews
    url: https://chrome.google.com/webstore/detail/lfoiekncpjoomigglgjildmjodpfmoif/reviews
    about: Leave a review or read feedback from other users
